### ISSUE TITLE
npm install fails for name change

### ISSUE THREAD

**Issue by NaanProphet** [mkormendy/node-alarm-dot-com#1]
Hi there!

`npm install node-alarmdotcom` was not working for me, so I had to use `npm install node-alarm-dot-com` this morning.

I also noticed that the npm page (https://www.npmjs.com/package/node-alarm-dot-com) is still pointed to the old GitHub page (https://github.com/mkormendy/node-alarm-dot-com) which is broken.

Maybe these things are already in the process of being updated, but just wanted to let others know.

**Comment by mkormendy** [comment]
My apologies, I had put in a request to npmjs.org support team to remove/rename the package as I found that there is a bit of an ecosystem of names around Alarm.com and then further found out about the frontpoint project which is at its' core an alarm.com interface with a separate authentication front-end.

For the time being, please use:

`npm install node-alarm-dot-com`

[https://www.npmjs.com/package/node-alarm-dot-com](https://www.npmjs.com/package/node-alarm-dot-com)
[https://github.com/mkormendy/node-alarm-dot-com](https://github.com/mkormendy/node-alarm-dot-com)

**Comment by mkormendy** [comment]
I have drastically changed this package to mirror work done by jhurliman.
The name and urls of the package will not change any further.
Please use:

`npm install node-alarm-dot-com`

https://www.npmjs.com/package/node-alarm-dot-com
https://github.com/mkormendy/node-alarm-dot-com

**Comment by NaanProphet** [comment]
Oh sure. I take it npmjs.org won't support the name change?

Personally I thought the name change to make it consistent with the other alarm.com APIs was a good idea.

**Comment by mkormendy** [comment]
Something like that.
