### ISSUE TITLE
Sensors not updating 

### ISSUE THREAD

**Issue by djstarr** [mkormendy/node-alarm-dot-com#2]
This project is awesome to remove the wrapapi dependency. Also love that the individual sensors show up in Home.app. Am seeing the sensors but the sensor states don’t seem to update in Home.app, eg when I open a door or window. Happy to help debug.

**Comment by djstarr** [comment]
Possibly should have put this in homebridge-node-alarm-for-com. Whoops.

**Comment by mkormendy** [comment]
Resolving issue in the related homebridge plugin github repo instead.
