### ISSUE TITLE
IgnoredDevices (to hide motion sensor from Homekit) not working

### ISSUE THREAD

**Issue by wmlorenzo** [mkormendy/node-alarm-dot-com#8]
I used the following code to hide a Motion sensor (similar to the sample code where “96922426-1” is replaced with the ID of the motion sensor that I found in my logs)

    "ignoredDevices": [
        "96922426-1",
    ]

However I can still see it in Homekit. Is there any other way I can hide a sensor?

I have tried restarting the HOOBS homebridge service and also rebooting the HOOBS device with no success.

I also tried replacing the ID of the Motion sensor with a Contact sensor to see if there was just an issue with the motion sensors however it still didn’t work. There seems to be an overall issue hiding sensors for my instance.

Otherwise, everything is working fine e.g. the sensors accurately show as open or closed, I can arm/disarm the alarm from homekit, etc.

Thanks

**Comment by mkormendy** [comment]
You may need to empty your accessory cache. See the pinned issue for more instructions. Also restarting your Home hub (iPad, or Homepod or Apple TV) helps after too.

**Comment by mkormendy** [comment]
This is the wrong project to post this issue in.
